server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pevu_social_commerce
    username: pevu_user
    password: Pevu123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: weagenthings@gmail.com
    password: veau smia bguv cpmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: pevu_super_secret_key_123

twilio:
  account-sid: your_twilio_account_sid
  auth-token: your_twilio_auth_token
  from-number: your_twilio_phone_number 