server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:weagenthings@gmail.com}
    password: ${MAIL_PASSWORD:veau smia bguv cpmr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET:pevu_super_secret_key_123}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your_twilio_account_sid}
  auth-token: ${TWILIO_AUTH_TOKEN:your_twilio_auth_token}
  from-number: ${TWILIO_FROM_NUMBER:your_twilio_phone_number} 