version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pevu_user
      POSTGRES_PASSWORD: Pevu123!
      POSTGRES_DB: pevu_social_commerce
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf

  frontend:
    build: ../../frontend/pevu-client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
    depends_on:
      - auth-service
      - product-service
      - media-service
      - user-profile-service
      - order-service
      - cart-wishlist-service

  auth-service:
    build: ../../backend/auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pevu_social_commerce
      SPRING_DATASOURCE_USERNAME: pevu_user
      SPRING_DATASOURCE_PASSWORD: Pevu123!
      JWT_SECRET: pevu_super_secret_key_123_very_long_and_secure_for_jwt_signing_256_bits_minimum_requirement
    ports:
      - '8081:8080'
    depends_on:
      - postgres

  product-service:
    build: ../../backend/product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pevu_social_commerce
      SPRING_DATASOURCE_USERNAME: pevu_user
      SPRING_DATASOURCE_PASSWORD: Pevu123!
    ports:
      - '8082:8080'
    depends_on:
      - postgres

  media-service:
    build: ../../backend/media-service
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    ports:
      - '8083:8080'
    depends_on:
      - minio

  user-profile-service:
    build: ../../backend/user-profile-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pevu_social_commerce
      SPRING_DATASOURCE_USERNAME: pevu_user
      SPRING_DATASOURCE_PASSWORD: Pevu123!
    ports:
      - '8084:8080'
    depends_on:
      - postgres

  order-service:
    build: ../../backend/order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pevu_social_commerce
      SPRING_DATASOURCE_USERNAME: pevu_user
      SPRING_DATASOURCE_PASSWORD: Pevu123!
    ports:
      - '8085:8080'
    depends_on:
      - postgres

  cart-wishlist-service:
    build: ../../backend/cart-wishlist-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pevu_social_commerce
      SPRING_DATASOURCE_USERNAME: pevu_user
      SPRING_DATASOURCE_PASSWORD: Pevu123!
    ports:
      - '8086:8087'
    depends_on:
      - postgres

  social-interaction-service:
    build: ../../backend/social-interaction-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pevu_social_commerce
      SPRING_DATASOURCE_USERNAME: pevu_user
      SPRING_DATASOURCE_PASSWORD: Pevu123!
    ports:
      - '8087:8086'
    depends_on:
      - postgres

volumes:
  pgdata:
  minio_data: 